### ISSUE TITLE
Error when serving the official detectron model

### ISSUE THREAD

**Issue by xinli94** [NVIDIA/dl-inference-server#19]
Hi,

I am using the official detectron model downloaded from `https://github.com/caffe2/models/tree/master/detectron/e2e_faster_rcnn_R-50-C4_1x`.

And I got this error
`terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at operator.cc:195] op. Cannot create operator of type 'GenerateProposals' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "rpn_cls_probs" input: "rpn_bbox_pred" input: "im_info" input: "anchor" output: "rpn_rois" output: "rpn_roi_probs" name: "" type: "GenerateProposals" arg { name: "nms_thres" f: 0.7 } arg { name: "min_size" f: 0 } arg { name: "spatial_scale" f: 0.0625 } arg { name: "correct_transform_coords" i: 1 } arg { name: "post_nms_topN" i: 1000 } arg { name: "pre_nms_topN" i: 6000 } device_option { device_type: 1 cuda_gpu_id: 0 }`

Is there anything I can do to fix this? Does inference server support detectron models?

Thanks so much for your help!

Best,
Xin

**Comment by deadeyegoodwin** [comment]
Thanks for reporting this issue. We will look into it and let you know what we find.

**Comment by deadeyegoodwin** [comment]
Have you seen this discussion? There seem to be some issues with detectron and C++/GPU.
https://github.com/facebookresearch/Detectron/issues/199

**Comment by xinli94** [comment]
> Have you seen this discussion? There seem to be some issues with detectron and C++/GPU.
> [facebookresearch/Detectron#199](https://github.com/facebookresearch/Detectron/issues/199)

Thanks and I am looking into it!

**Comment by deadeyegoodwin** [comment]
Thank you for the question. We'd be interested in hearing any progress you have, especially with the newly open-sourced version of the TensorRT Inference Server at https://github.com/NVIDIA/tensorrt-inference-server. Please re-raise your issue there and is possible provide more details about your requirements. Since the server is now open-source you also have the option of experimenting with a change yourself.

This repo is no longer accepting changes and will soon be closed so please move all future work to https://github.com/NVIDIA/tensorrt-inference-server.
