### ISSUE TITLE
File-based array sending (via URI)

### ISSUE THREAD

**Issue by seovchinnikov** [NVIDIA/dl-inference-server#24]
Hey!
Thank you for your framework.
Do you have any plans to add support of file based array sending via uri (real case is common filesystem between server and clients and in-RAM fs in particular)? POST of big arrays is not the best method for some cases.
Thank you!

**Comment by deadeyegoodwin** [comment]
Thank you for the question. As of now we have no plans to implement a file-based API to the inference server.

The entire TensorRT Inference Server has been open-sourced at https://github.com/NVIDIA/tensorrt-inference-server. Please re-raise your issue there and is possible provide more details about your requirements. Since the server is now open-source you also have the option of experimenting with a change yourself.

This repo is no longer accepting changes and will soon be closed so please move all future work to https://github.com/NVIDIA/tensorrt-inference-server.
